kind: Service
apiVersion: v1
metadata:
  name: {{ .Chart.Name }}
  namespace: {{ .Values.namespace.sso }}
  labels:
    group: afad
spec:
  selector:
    app: {{ .Chart.Name }}
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
    - name: grpc
      protocol: TCP
      port: 6565
      targetPort: 6565
  type: ClusterIP
